workflows:
  ios-workflow:
    name: Build iOS App
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install Flutter dependencies
        script: |
          cd $CM_BUILD_DIR
          flutter pub get

      - name: Generate flutter_export_environment
        script: |
          cd $CM_BUILD_DIR/ios/Flutter
          echo "export FLUTTER_ROOT=$FLUTTER_ROOT" > flutter_export_environment
          echo "export FLUTTER_APPLICATION_PATH=$CM_BUILD_DIR" >> flutter_export_environment
          echo "export COCOAPODS_PARALLEL_CODE_SIGN=true" >> flutter_export_environment
          echo "export FLUTTER_TARGET=lib/main.dart" >> flutter_export_environment
          echo "export FLUTTER_BUILD_DIR=build" >> flutter_export_environment
          echo "export SYMROOT=\${SOURCE_ROOT}/../build/ios" >> flutter_export_environment
          echo "export FLUTTER_BUILD_NAME=1.0.0" >> flutter_export_environment
          echo "export FLUTTER_BUILD_NUMBER=1" >> flutter_export_environment
          echo "export DART_OBFUSCATION=false" >> flutter_export_environment
          echo "export TRACK_WIDGET_CREATION=true" >> flutter_export_environment
          echo "export TREE_SHAKE_ICONS=false" >> flutter_export_environment
          echo "export PACKAGE_CONFIG=.dart_tool/package_config.json" >> flutter_export_environment

      - name: Build iOS app
        script: |
          flutter build ios --release --no-codesign

    artifacts:
      - build/ios/iphoneos/*.app
      - build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - andronix.r@gmail.com
