workflows:
  ios-build:
    name: iOS Build
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Clean previous pods
        script: |
          cd $CM_BUILD_DIR/ios
          rm -rf Pods Podfile.lock

      - name: Install Flutter dependencies
        script: |
          cd $CM_BUILD_DIR
          flutter pub get

      - name: Install iOS pods
        script: |
          cd $CM_BUILD_DIR/ios
          pod install

      - name: Flutter build iOS
        script: |
          cd $CM_BUILD_DIR
          flutter build ios --release --no-codesign

    artifacts:
      - build/ios/iphoneos/*.ipa
      - build/ios/iphoneos/Runner.app
    publishing:
      email:
        recipients:
          - andronix.r@gmail.com
        notify:
          success: true
          failure: true
