workflows:
  ios-build:
    name: iOS Build
    environment:
      flutter: stable
      xcode: latest
      vars:
        FLUTTER_BUILD_NAME: "1.0.0"
        FLUTTER_BUILD_NUMBER: "1"
    scripts:
      - name: Clean previous pods
        script: |
          cd $CM_BUILD_DIR/ios
          rm -rf Pods Podfile.lock

      - name: Install Flutter dependencies
        script: |
          cd $CM_BUILD_DIR
          flutter pub get

      - name: Generate flutter_export_environment
        script: |
          cd $CM_BUILD_DIR/ios/Flutter
          mkdir -p .
          echo "FLUTTER_ROOT=$FLUTTER_ROOT" > flutter_export_environment
          echo "FLUTTER_APPLICATION_PATH=$CM_BUILD_DIR" >> flutter_export_environment
          echo "COCOAPODS_PARALLEL_CODE_SIGN=true" >> flutter_export_environment
          echo "FLUTTER_TARGET=lib/main.dart" >> flutter_export_environment
          echo "FLUTTER_BUILD_DIR=build" >> flutter_export_environment
          echo "SYMROOT=${SOURCE_ROOT}/../build/ios" >> flutter_export_environment
          echo "FLUTTER_BUILD_NAME=$FLUTTER_BUILD_NAME" >> flutter_export_environment
          echo "FLUTTER_BUILD_NUMBER=$FLUTTER_BUILD_NUMBER" >> flutter_export_environment
          echo "DART_OBFUSCATION=false" >> flutter_export_environment
          echo "TRACK_WIDGET_CREATION=true" >> flutter_export_environment
          echo "TREE_SHAKE_ICONS=false" >> flutter_export_environment
          echo "PACKAGE_CONFIG=.dart_tool/package_config.json" >> flutter_export_environment

      - name: Install iOS pods
        script: |
          cd $CM_BUILD_DIR/ios
          pod install --verbose

      - name: Flutter build iOS
        script: |
          cd $CM_BUILD_DIR
          flutter build ios --release --no-codesign

    artifacts:
      - build/ios/iphoneos/*.ipa
      - build/ios/iphoneos/Runner.app

    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
