workflows:
  ios-build:
    name: iOS Build
    environment:
      flutter: stable
      xcode: latest
      vars:
        FLUTTER_BUILD_NAME: "1.0.0"
        FLUTTER_BUILD_NUMBER: "1"
    scripts:
      - name: Clean previous pods
        script: |
          cd $CM_BUILD_DIR/ios
          rm -rf Pods Podfile.lock

      - name: Install Flutter dependencies
        script: |
          cd $CM_BUILD_DIR
          flutter pub get

      - name: Generate flutter_export_environment (pure Ruby)
        script: |
          cd $CM_BUILD_DIR/ios/Flutter
          mkdir -p .
          cat <<'EOF' > flutter_export_environment
            ENV['FLUTTER_ROOT']               = '$FLUTTER_ROOT'
            ENV['FLUTTER_APPLICATION_PATH']   = '$CM_BUILD_DIR'
            ENV['COCOAPODS_PARALLEL_CODE_SIGN']= 'true'
            ENV['FLUTTER_TARGET']             = 'lib/main.dart'
            ENV['FLUTTER_BUILD_DIR']          = 'build'
            ENV['SYMROOT']                    = '${SOURCE_ROOT}/../build/ios'
            ENV['FLUTTER_BUILD_NAME']         = '$FLUTTER_BUILD_NAME'
            ENV['FLUTTER_BUILD_NUMBER']       = '$FLUTTER_BUILD_NUMBER'
            ENV['DART_OBFUSCATION']           = 'false'
            ENV['TRACK_WIDGET_CREATION']      = 'true'
            ENV['TREE_SHAKE_ICONS']           = 'false'
            ENV['PACKAGE_CONFIG']             = '.dart_tool/package_config.json'
            EOF

      - name: Install iOS pods
        script: |
          cd $CM_BUILD_DIR/ios
          pod install --verbose

      - name: Flutter build iOS
        script: |
          cd $CM_BUILD_DIR
          flutter build ios --release --no-codesign

    artifacts:
      - build/ios/iphoneos/*.ipa
      - build/ios/iphoneos/Runner.app

    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
