workflows:
  ios-build:
    name: iOS Build for AltStore
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install Flutter dependencies
        script: |
          cd $CM_BUILD_DIR
          flutter pub get

      - name: Build iOS Archive
        script: |
          cd $CM_BUILD_DIR
          flutter build ipa --no-codesign

      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath build/ios/archive/Runner.xcarchive \
            -exportOptionsPlist ios/ExportOptions.plist \
            -exportPath build/ios/ipa

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - lonelyonmoon@gmail.com
        notify:
          success: true
          failure: true
