platform :ios, '13.0'

# Отключаем статистику CocoaPods
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

# Путь к flutter внутри CI
def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('Pods', 'Target Support Files', 'Pods-Runner', 'Pods-Runner.release.xcconfig'))
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end
  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}"
end

# Подключаем helper из Flutter SDK
load File.join(__dir__, 'Flutter', 'podhelper.rb')
flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Здесь подключаются все iOS-поды из pubspec.yaml
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  flutter_post_install(installer)
end
