workflows:
  ios-workflow:
    name: Build iOS without Code Signing
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "*"
          include: true
          source: true
    scripts:
      - name: Install Flutter dependencies
        script: |
          cd $CM_BUILD_DIR
          flutter pub get
      - name: Build iOS app
        script: |
          cd $CM_BUILD_DIR
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/*.app
      - build/ios/ipa/*.ipa
      - build/ios/Build/**/*.dSYM
    publishing:
      email:
        recipients:
          - andronix.r@gmail.com